export const businessCategories = [
  "Cafe",
  "Restoran",
  "Berber",
  "Kuaför",
  "Diş Kliniği",
  "Çiçekçi",
  "Güzellik Salonu",
  "Spor Salonu",
  "Oto Yıkama",
  "Veteriner",
  "Emlak Ofisi",
  "Otel",
  "Pastane",
  "Market",
  "Mobilya Mağazası",
  "Butik",
  "Telefoncu",
  "Eczane",
];
